# coding: utf-8

"""
    Infoplus API

    Infoplus API.  # noqa: E501

    OpenAPI spec version: v3.0
    Contact: api@infopluscommerce.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Infoplus
from Infoplus.api.service_type_api import ServiceTypeApi  # noqa: E501
from Infoplus.rest import ApiException


class TestServiceTypeApi(unittest.TestCase):
    """ServiceTypeApi unit test stubs"""

    def setUp(self):
        self.api = Infoplus.api.service_type_api.ServiceTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_service_type_by_id(self):
        """Test case for get_service_type_by_id

        Get a serviceType by id  # noqa: E501
        """
        pass

    def test_get_service_type_by_search_text(self):
        """Test case for get_service_type_by_search_text

        Search serviceTypes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
