# coding: utf-8

"""
    Infoplus API

    Infoplus API.  # noqa: E501

    OpenAPI spec version: beta
    Contact: api@infopluscommerce.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Infoplus
from Infoplus.api.return_order_api import ReturnOrderApi  # noqa: E501
from Infoplus.rest import ApiException


class TestReturnOrderApi(unittest.TestCase):
    """ReturnOrderApi unit test stubs"""

    def setUp(self):
        self.api = Infoplus.api.return_order_api.ReturnOrderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_return_order_audit(self):
        """Test case for add_return_order_audit

        Add new audit for a returnOrder  # noqa: E501
        """
        pass

    def test_add_return_order_file(self):
        """Test case for add_return_order_file

        Attach a file to a returnOrder  # noqa: E501
        """
        pass

    def test_add_return_order_file_by_url(self):
        """Test case for add_return_order_file_by_url

        Attach a file to a returnOrder by URL.  # noqa: E501
        """
        pass

    def test_add_return_order_tag(self):
        """Test case for add_return_order_tag

        Add new tags for a returnOrder.  # noqa: E501
        """
        pass

    def test_delete_return_order_file(self):
        """Test case for delete_return_order_file

        Delete a file for a returnOrder.  # noqa: E501
        """
        pass

    def test_delete_return_order_tag(self):
        """Test case for delete_return_order_tag

        Delete a tag for a returnOrder.  # noqa: E501
        """
        pass

    def test_get_duplicate_return_order_by_id(self):
        """Test case for get_duplicate_return_order_by_id

        Get a duplicated a returnOrder by id  # noqa: E501
        """
        pass

    def test_get_return_order_by_filter(self):
        """Test case for get_return_order_by_filter

        Search returnOrders by filter  # noqa: E501
        """
        pass

    def test_get_return_order_by_id(self):
        """Test case for get_return_order_by_id

        Get a returnOrder by id  # noqa: E501
        """
        pass

    def test_get_return_order_files(self):
        """Test case for get_return_order_files

        Get the files for a returnOrder.  # noqa: E501
        """
        pass

    def test_get_return_order_tags(self):
        """Test case for get_return_order_tags

        Get the tags for a returnOrder.  # noqa: E501
        """
        pass

    def test_update_return_order(self):
        """Test case for update_return_order

        Update a returnOrder  # noqa: E501
        """
        pass

    def test_update_return_order_custom_fields(self):
        """Test case for update_return_order_custom_fields

        Update a returnOrder custom fields  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
