# coding: utf-8

"""
    Infoplus API

    Infoplus API.  # noqa: E501

    OpenAPI spec version: beta
    Contact: api@infopluscommerce.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Infoplus
from Infoplus.api.customer_api import CustomerApi  # noqa: E501
from Infoplus.rest import ApiException


class TestCustomerApi(unittest.TestCase):
    """CustomerApi unit test stubs"""

    def setUp(self):
        self.api = Infoplus.api.customer_api.CustomerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_customer(self):
        """Test case for add_customer

        Create a customer  # noqa: E501
        """
        pass

    def test_add_customer_audit(self):
        """Test case for add_customer_audit

        Add new audit for a customer  # noqa: E501
        """
        pass

    def test_add_customer_file(self):
        """Test case for add_customer_file

        Attach a file to a customer  # noqa: E501
        """
        pass

    def test_add_customer_tag(self):
        """Test case for add_customer_tag

        Add new tags for a customer.  # noqa: E501
        """
        pass

    def test_delete_customer(self):
        """Test case for delete_customer

        Delete a customer  # noqa: E501
        """
        pass

    def test_delete_customer_tag(self):
        """Test case for delete_customer_tag

        Delete a tag for a customer.  # noqa: E501
        """
        pass

    def test_get_by_customer_no(self):
        """Test case for get_by_customer_no

        Get a customer by Customer No  # noqa: E501
        """
        pass

    def test_get_customer_by_filter(self):
        """Test case for get_customer_by_filter

        Search customers by filter  # noqa: E501
        """
        pass

    def test_get_customer_by_id(self):
        """Test case for get_customer_by_id

        Get a customer by id  # noqa: E501
        """
        pass

    def test_get_customer_tags(self):
        """Test case for get_customer_tags

        Get the tags for a customer.  # noqa: E501
        """
        pass

    def test_get_duplicate_customer_by_id(self):
        """Test case for get_duplicate_customer_by_id

        Get a duplicated a customer by id  # noqa: E501
        """
        pass

    def test_update_customer(self):
        """Test case for update_customer

        Update a customer  # noqa: E501
        """
        pass

    def test_update_customer_custom_fields(self):
        """Test case for update_customer_custom_fields

        Update a customer custom fields  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
