# coding: utf-8

"""
    Infoplus API

    Infoplus API.  # noqa: E501

    OpenAPI spec version: v3.0
    Contact: api@infopluscommerce.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Infoplus
from Infoplus.api.billing_code_type_api import BillingCodeTypeApi  # noqa: E501
from Infoplus.rest import ApiException


class TestBillingCodeTypeApi(unittest.TestCase):
    """BillingCodeTypeApi unit test stubs"""

    def setUp(self):
        self.api = Infoplus.api.billing_code_type_api.BillingCodeTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_billing_code_type(self):
        """Test case for add_billing_code_type

        Create a billingCodeType  # noqa: E501
        """
        pass

    def test_add_billing_code_type_audit(self):
        """Test case for add_billing_code_type_audit

        Add new audit for a billingCodeType  # noqa: E501
        """
        pass

    def test_add_billing_code_type_file(self):
        """Test case for add_billing_code_type_file

        Attach a file to a billingCodeType  # noqa: E501
        """
        pass

    def test_add_billing_code_type_file_by_url(self):
        """Test case for add_billing_code_type_file_by_url

        Attach a file to a billingCodeType by URL.  # noqa: E501
        """
        pass

    def test_add_billing_code_type_tag(self):
        """Test case for add_billing_code_type_tag

        Add new tags for a billingCodeType.  # noqa: E501
        """
        pass

    def test_delete_billing_code_type(self):
        """Test case for delete_billing_code_type

        Delete a billingCodeType  # noqa: E501
        """
        pass

    def test_delete_billing_code_type_file(self):
        """Test case for delete_billing_code_type_file

        Delete a file for a billingCodeType.  # noqa: E501
        """
        pass

    def test_delete_billing_code_type_tag(self):
        """Test case for delete_billing_code_type_tag

        Delete a tag for a billingCodeType.  # noqa: E501
        """
        pass

    def test_get_billing_code_type_by_filter(self):
        """Test case for get_billing_code_type_by_filter

        Search billingCodeTypes by filter  # noqa: E501
        """
        pass

    def test_get_billing_code_type_by_id(self):
        """Test case for get_billing_code_type_by_id

        Get a billingCodeType by id  # noqa: E501
        """
        pass

    def test_get_billing_code_type_files(self):
        """Test case for get_billing_code_type_files

        Get the files for a billingCodeType.  # noqa: E501
        """
        pass

    def test_get_billing_code_type_tags(self):
        """Test case for get_billing_code_type_tags

        Get the tags for a billingCodeType.  # noqa: E501
        """
        pass

    def test_get_duplicate_billing_code_type_by_id(self):
        """Test case for get_duplicate_billing_code_type_by_id

        Get a duplicated a billingCodeType by id  # noqa: E501
        """
        pass

    def test_update_billing_code_type(self):
        """Test case for update_billing_code_type

        Update a billingCodeType  # noqa: E501
        """
        pass

    def test_update_billing_code_type_custom_fields(self):
        """Test case for update_billing_code_type_custom_fields

        Update a billingCodeType custom fields  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
