# coding: utf-8

"""
    Infoplus API

    Infoplus API.  # noqa: E501

    OpenAPI spec version: beta
    Contact: api@infopluscommerce.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from Infoplus.api_client import ApiClient


class Gs1128LabelApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_gs1128_label_audit(self, gs1128_label_id, gs1128_label_audit, **kwargs):  # noqa: E501
        """Add new audit for a gs1128Label  # noqa: E501

        Adds an audit to an existing gs1128Label.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.add_gs1128_label_audit(gs1128_label_id, gs1128_label_audit, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to add an audit to (required)
        :param str gs1128_label_audit: The audit to add (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.add_gs1128_label_audit_with_http_info(gs1128_label_id, gs1128_label_audit, **kwargs)  # noqa: E501
        else:
            (data) = self.add_gs1128_label_audit_with_http_info(gs1128_label_id, gs1128_label_audit, **kwargs)  # noqa: E501
            return data

    def add_gs1128_label_audit_with_http_info(self, gs1128_label_id, gs1128_label_audit, **kwargs):  # noqa: E501
        """Add new audit for a gs1128Label  # noqa: E501

        Adds an audit to an existing gs1128Label.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.add_gs1128_label_audit_with_http_info(gs1128_label_id, gs1128_label_audit, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to add an audit to (required)
        :param str gs1128_label_audit: The audit to add (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['gs1128_label_id', 'gs1128_label_audit']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_gs1128_label_audit" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'gs1128_label_id' is set
        if ('gs1128_label_id' not in params or
                params['gs1128_label_id'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_id` when calling `add_gs1128_label_audit`")  # noqa: E501
        # verify the required parameter 'gs1128_label_audit' is set
        if ('gs1128_label_audit' not in params or
                params['gs1128_label_audit'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_audit` when calling `add_gs1128_label_audit`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'gs1128_label_id' in params:
            path_params['gs1128LabelId'] = params['gs1128_label_id']  # noqa: E501
        if 'gs1128_label_audit' in params:
            path_params['gs1128LabelAudit'] = params['gs1128_label_audit']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/{gs1128LabelId}/audit/{gs1128LabelAudit}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def add_gs1128_label_file(self, gs1128_label_id, file_name, **kwargs):  # noqa: E501
        """Attach a file to a gs1128Label  # noqa: E501

        Adds a file to an existing gs1128Label.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.add_gs1128_label_file(gs1128_label_id, file_name, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to add a file to (required)
        :param str file_name: Name of file (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.add_gs1128_label_file_with_http_info(gs1128_label_id, file_name, **kwargs)  # noqa: E501
        else:
            (data) = self.add_gs1128_label_file_with_http_info(gs1128_label_id, file_name, **kwargs)  # noqa: E501
            return data

    def add_gs1128_label_file_with_http_info(self, gs1128_label_id, file_name, **kwargs):  # noqa: E501
        """Attach a file to a gs1128Label  # noqa: E501

        Adds a file to an existing gs1128Label.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.add_gs1128_label_file_with_http_info(gs1128_label_id, file_name, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to add a file to (required)
        :param str file_name: Name of file (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['gs1128_label_id', 'file_name']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_gs1128_label_file" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'gs1128_label_id' is set
        if ('gs1128_label_id' not in params or
                params['gs1128_label_id'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_id` when calling `add_gs1128_label_file`")  # noqa: E501
        # verify the required parameter 'file_name' is set
        if ('file_name' not in params or
                params['file_name'] is None):
            raise ValueError("Missing the required parameter `file_name` when calling `add_gs1128_label_file`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'gs1128_label_id' in params:
            path_params['gs1128LabelId'] = params['gs1128_label_id']  # noqa: E501
        if 'file_name' in params:
            path_params['fileName'] = params['file_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/{gs1128LabelId}/file/{fileName}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def add_gs1128_label_file_by_url(self, body, gs1128_label_id, **kwargs):  # noqa: E501
        """Attach a file to a gs1128Label by URL.  # noqa: E501

        Adds a file to an existing gs1128Label by URL.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.add_gs1128_label_file_by_url(body, gs1128_label_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param RecordFile body: The url and optionly fileName to be used. (required)
        :param int gs1128_label_id: Id of the gs1128Label to add an file to (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.add_gs1128_label_file_by_url_with_http_info(body, gs1128_label_id, **kwargs)  # noqa: E501
        else:
            (data) = self.add_gs1128_label_file_by_url_with_http_info(body, gs1128_label_id, **kwargs)  # noqa: E501
            return data

    def add_gs1128_label_file_by_url_with_http_info(self, body, gs1128_label_id, **kwargs):  # noqa: E501
        """Attach a file to a gs1128Label by URL.  # noqa: E501

        Adds a file to an existing gs1128Label by URL.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.add_gs1128_label_file_by_url_with_http_info(body, gs1128_label_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param RecordFile body: The url and optionly fileName to be used. (required)
        :param int gs1128_label_id: Id of the gs1128Label to add an file to (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'gs1128_label_id']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_gs1128_label_file_by_url" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `add_gs1128_label_file_by_url`")  # noqa: E501
        # verify the required parameter 'gs1128_label_id' is set
        if ('gs1128_label_id' not in params or
                params['gs1128_label_id'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_id` when calling `add_gs1128_label_file_by_url`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'gs1128_label_id' in params:
            path_params['gs1128LabelId'] = params['gs1128_label_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/{gs1128LabelId}/file', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def add_gs1128_label_tag(self, gs1128_label_id, gs1128_label_tag, **kwargs):  # noqa: E501
        """Add new tags for a gs1128Label.  # noqa: E501

        Adds a tag to an existing gs1128Label.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.add_gs1128_label_tag(gs1128_label_id, gs1128_label_tag, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to add a tag to (required)
        :param str gs1128_label_tag: The tag to add (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.add_gs1128_label_tag_with_http_info(gs1128_label_id, gs1128_label_tag, **kwargs)  # noqa: E501
        else:
            (data) = self.add_gs1128_label_tag_with_http_info(gs1128_label_id, gs1128_label_tag, **kwargs)  # noqa: E501
            return data

    def add_gs1128_label_tag_with_http_info(self, gs1128_label_id, gs1128_label_tag, **kwargs):  # noqa: E501
        """Add new tags for a gs1128Label.  # noqa: E501

        Adds a tag to an existing gs1128Label.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.add_gs1128_label_tag_with_http_info(gs1128_label_id, gs1128_label_tag, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to add a tag to (required)
        :param str gs1128_label_tag: The tag to add (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['gs1128_label_id', 'gs1128_label_tag']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_gs1128_label_tag" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'gs1128_label_id' is set
        if ('gs1128_label_id' not in params or
                params['gs1128_label_id'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_id` when calling `add_gs1128_label_tag`")  # noqa: E501
        # verify the required parameter 'gs1128_label_tag' is set
        if ('gs1128_label_tag' not in params or
                params['gs1128_label_tag'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_tag` when calling `add_gs1128_label_tag`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'gs1128_label_id' in params:
            path_params['gs1128LabelId'] = params['gs1128_label_id']  # noqa: E501
        if 'gs1128_label_tag' in params:
            path_params['gs1128LabelTag'] = params['gs1128_label_tag']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/{gs1128LabelId}/tag/{gs1128LabelTag}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_gs1128_label(self, gs1128_label_id, **kwargs):  # noqa: E501
        """Delete a gs1128Label  # noqa: E501

        Deletes the gs1128Label identified by the specified id.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.delete_gs1128_label(gs1128_label_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to be deleted. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.delete_gs1128_label_with_http_info(gs1128_label_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_gs1128_label_with_http_info(gs1128_label_id, **kwargs)  # noqa: E501
            return data

    def delete_gs1128_label_with_http_info(self, gs1128_label_id, **kwargs):  # noqa: E501
        """Delete a gs1128Label  # noqa: E501

        Deletes the gs1128Label identified by the specified id.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.delete_gs1128_label_with_http_info(gs1128_label_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to be deleted. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['gs1128_label_id']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_gs1128_label" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'gs1128_label_id' is set
        if ('gs1128_label_id' not in params or
                params['gs1128_label_id'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_id` when calling `delete_gs1128_label`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'gs1128_label_id' in params:
            path_params['gs1128LabelId'] = params['gs1128_label_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/{gs1128LabelId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_gs1128_label_file(self, gs1128_label_id, file_id, **kwargs):  # noqa: E501
        """Delete a file for a gs1128Label.  # noqa: E501

        Deletes an existing gs1128Label file using the specified data.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.delete_gs1128_label_file(gs1128_label_id, file_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to remove file from (required)
        :param int file_id: Id of the file to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.delete_gs1128_label_file_with_http_info(gs1128_label_id, file_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_gs1128_label_file_with_http_info(gs1128_label_id, file_id, **kwargs)  # noqa: E501
            return data

    def delete_gs1128_label_file_with_http_info(self, gs1128_label_id, file_id, **kwargs):  # noqa: E501
        """Delete a file for a gs1128Label.  # noqa: E501

        Deletes an existing gs1128Label file using the specified data.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.delete_gs1128_label_file_with_http_info(gs1128_label_id, file_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to remove file from (required)
        :param int file_id: Id of the file to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['gs1128_label_id', 'file_id']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_gs1128_label_file" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'gs1128_label_id' is set
        if ('gs1128_label_id' not in params or
                params['gs1128_label_id'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_id` when calling `delete_gs1128_label_file`")  # noqa: E501
        # verify the required parameter 'file_id' is set
        if ('file_id' not in params or
                params['file_id'] is None):
            raise ValueError("Missing the required parameter `file_id` when calling `delete_gs1128_label_file`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'gs1128_label_id' in params:
            path_params['gs1128LabelId'] = params['gs1128_label_id']  # noqa: E501
        if 'file_id' in params:
            path_params['fileId'] = params['file_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/{gs1128LabelId}/file/{fileId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_gs1128_label_tag(self, gs1128_label_id, gs1128_label_tag, **kwargs):  # noqa: E501
        """Delete a tag for a gs1128Label.  # noqa: E501

        Deletes an existing gs1128Label tag using the specified data.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.delete_gs1128_label_tag(gs1128_label_id, gs1128_label_tag, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to remove tag from (required)
        :param str gs1128_label_tag: The tag to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.delete_gs1128_label_tag_with_http_info(gs1128_label_id, gs1128_label_tag, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_gs1128_label_tag_with_http_info(gs1128_label_id, gs1128_label_tag, **kwargs)  # noqa: E501
            return data

    def delete_gs1128_label_tag_with_http_info(self, gs1128_label_id, gs1128_label_tag, **kwargs):  # noqa: E501
        """Delete a tag for a gs1128Label.  # noqa: E501

        Deletes an existing gs1128Label tag using the specified data.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.delete_gs1128_label_tag_with_http_info(gs1128_label_id, gs1128_label_tag, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to remove tag from (required)
        :param str gs1128_label_tag: The tag to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['gs1128_label_id', 'gs1128_label_tag']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_gs1128_label_tag" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'gs1128_label_id' is set
        if ('gs1128_label_id' not in params or
                params['gs1128_label_id'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_id` when calling `delete_gs1128_label_tag`")  # noqa: E501
        # verify the required parameter 'gs1128_label_tag' is set
        if ('gs1128_label_tag' not in params or
                params['gs1128_label_tag'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_tag` when calling `delete_gs1128_label_tag`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'gs1128_label_id' in params:
            path_params['gs1128LabelId'] = params['gs1128_label_id']  # noqa: E501
        if 'gs1128_label_tag' in params:
            path_params['gs1128LabelTag'] = params['gs1128_label_tag']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/{gs1128LabelId}/tag/{gs1128LabelTag}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_duplicate_gs1128_label_by_id(self, gs1128_label_id, **kwargs):  # noqa: E501
        """Get a duplicated a gs1128Label by id  # noqa: E501

        Returns a duplicated gs1128Label identified by the specified id.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.get_duplicate_gs1128_label_by_id(gs1128_label_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to be duplicated. (required)
        :return: Gs1128Label
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.get_duplicate_gs1128_label_by_id_with_http_info(gs1128_label_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_duplicate_gs1128_label_by_id_with_http_info(gs1128_label_id, **kwargs)  # noqa: E501
            return data

    def get_duplicate_gs1128_label_by_id_with_http_info(self, gs1128_label_id, **kwargs):  # noqa: E501
        """Get a duplicated a gs1128Label by id  # noqa: E501

        Returns a duplicated gs1128Label identified by the specified id.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.get_duplicate_gs1128_label_by_id_with_http_info(gs1128_label_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to be duplicated. (required)
        :return: Gs1128Label
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['gs1128_label_id']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_duplicate_gs1128_label_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'gs1128_label_id' is set
        if ('gs1128_label_id' not in params or
                params['gs1128_label_id'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_id` when calling `get_duplicate_gs1128_label_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'gs1128_label_id' in params:
            path_params['gs1128LabelId'] = params['gs1128_label_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/duplicate/{gs1128LabelId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Gs1128Label',  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_gs1128_label_by_filter(self, **kwargs):  # noqa: E501
        """Search gs1128Labels by filter  # noqa: E501

        Returns the list of gs1128Labels that match the given filter.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.get_gs1128_label_by_filter(_async=True)
        >>> result = thread.get()

        :param _async bool
        :param str filter: Query string, used to filter results.
        :param int page: Result page number.  Defaults to 1.
        :param int limit: Maximum results per page.  Defaults to 20.  Max allowed value is 250.
        :param str sort: Sort results by specified field.
        :return: list[Gs1128Label]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.get_gs1128_label_by_filter_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_gs1128_label_by_filter_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_gs1128_label_by_filter_with_http_info(self, **kwargs):  # noqa: E501
        """Search gs1128Labels by filter  # noqa: E501

        Returns the list of gs1128Labels that match the given filter.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.get_gs1128_label_by_filter_with_http_info(_async=True)
        >>> result = thread.get()

        :param _async bool
        :param str filter: Query string, used to filter results.
        :param int page: Result page number.  Defaults to 1.
        :param int limit: Maximum results per page.  Defaults to 20.  Max allowed value is 250.
        :param str sort: Sort results by specified field.
        :return: list[Gs1128Label]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter', 'page', 'limit', 'sort']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_gs1128_label_by_filter" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filter' in params:
            query_params.append(('filter', params['filter']))  # noqa: E501
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'sort' in params:
            query_params.append(('sort', params['sort']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/search', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Gs1128Label]',  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_gs1128_label_by_id(self, gs1128_label_id, **kwargs):  # noqa: E501
        """Get a gs1128Label by id  # noqa: E501

        Returns the gs1128Label identified by the specified id.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.get_gs1128_label_by_id(gs1128_label_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to be returned. (required)
        :return: Gs1128Label
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.get_gs1128_label_by_id_with_http_info(gs1128_label_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_gs1128_label_by_id_with_http_info(gs1128_label_id, **kwargs)  # noqa: E501
            return data

    def get_gs1128_label_by_id_with_http_info(self, gs1128_label_id, **kwargs):  # noqa: E501
        """Get a gs1128Label by id  # noqa: E501

        Returns the gs1128Label identified by the specified id.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.get_gs1128_label_by_id_with_http_info(gs1128_label_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to be returned. (required)
        :return: Gs1128Label
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['gs1128_label_id']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_gs1128_label_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'gs1128_label_id' is set
        if ('gs1128_label_id' not in params or
                params['gs1128_label_id'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_id` when calling `get_gs1128_label_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'gs1128_label_id' in params:
            path_params['gs1128LabelId'] = params['gs1128_label_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/{gs1128LabelId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Gs1128Label',  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_gs1128_label_files(self, gs1128_label_id, **kwargs):  # noqa: E501
        """Get the files for a gs1128Label.  # noqa: E501

        Get all existing gs1128Label files.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.get_gs1128_label_files(gs1128_label_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to get files for (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.get_gs1128_label_files_with_http_info(gs1128_label_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_gs1128_label_files_with_http_info(gs1128_label_id, **kwargs)  # noqa: E501
            return data

    def get_gs1128_label_files_with_http_info(self, gs1128_label_id, **kwargs):  # noqa: E501
        """Get the files for a gs1128Label.  # noqa: E501

        Get all existing gs1128Label files.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.get_gs1128_label_files_with_http_info(gs1128_label_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to get files for (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['gs1128_label_id']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_gs1128_label_files" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'gs1128_label_id' is set
        if ('gs1128_label_id' not in params or
                params['gs1128_label_id'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_id` when calling `get_gs1128_label_files`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'gs1128_label_id' in params:
            path_params['gs1128LabelId'] = params['gs1128_label_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/{gs1128LabelId}/file', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_gs1128_label_tags(self, gs1128_label_id, **kwargs):  # noqa: E501
        """Get the tags for a gs1128Label.  # noqa: E501

        Get all existing gs1128Label tags.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.get_gs1128_label_tags(gs1128_label_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to get tags for (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.get_gs1128_label_tags_with_http_info(gs1128_label_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_gs1128_label_tags_with_http_info(gs1128_label_id, **kwargs)  # noqa: E501
            return data

    def get_gs1128_label_tags_with_http_info(self, gs1128_label_id, **kwargs):  # noqa: E501
        """Get the tags for a gs1128Label.  # noqa: E501

        Get all existing gs1128Label tags.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.get_gs1128_label_tags_with_http_info(gs1128_label_id, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param int gs1128_label_id: Id of the gs1128Label to get tags for (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['gs1128_label_id']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_gs1128_label_tags" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'gs1128_label_id' is set
        if ('gs1128_label_id' not in params or
                params['gs1128_label_id'] is None):
            raise ValueError("Missing the required parameter `gs1128_label_id` when calling `get_gs1128_label_tags`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'gs1128_label_id' in params:
            path_params['gs1128LabelId'] = params['gs1128_label_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/{gs1128LabelId}/tag', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_gs1128_label_custom_fields(self, body, **kwargs):  # noqa: E501
        """Update a gs1128Label custom fields  # noqa: E501

        Updates an existing gs1128Label custom fields using the specified data.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.update_gs1128_label_custom_fields(body, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param Gs1128Label body: Gs1128Label to be updated. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('_async'):
            return self.update_gs1128_label_custom_fields_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.update_gs1128_label_custom_fields_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def update_gs1128_label_custom_fields_with_http_info(self, body, **kwargs):  # noqa: E501
        """Update a gs1128Label custom fields  # noqa: E501

        Updates an existing gs1128Label custom fields using the specified data.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass _async=True
        >>> thread = api.update_gs1128_label_custom_fields_with_http_info(body, _async=True)
        >>> result = thread.get()

        :param _async bool
        :param Gs1128Label body: Gs1128Label to be updated. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('_async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_gs1128_label_custom_fields" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `update_gs1128_label_custom_fields`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/gs1128Label/customFields', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            _async=params.get('_async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
