# coding: utf-8

"""
    Infoplus API

    Infoplus API.  # noqa: E501

    OpenAPI spec version: beta
    Contact: api@infopluscommerce.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from Infoplus.api_client import ApiClient


class ItemBuyerApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_item_buyer(self, body, **kwargs):  # noqa: E501
        """Create an itemBuyer  # noqa: E501

        Inserts a new itemBuyer using the specified data.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.add_item_buyer(body, async=True)
        >>> result = thread.get()

        :param async bool
        :param ItemBuyer body: ItemBuyer to be inserted. (required)
        :return: ItemBuyer
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.add_item_buyer_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.add_item_buyer_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def add_item_buyer_with_http_info(self, body, **kwargs):  # noqa: E501
        """Create an itemBuyer  # noqa: E501

        Inserts a new itemBuyer using the specified data.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.add_item_buyer_with_http_info(body, async=True)
        >>> result = thread.get()

        :param async bool
        :param ItemBuyer body: ItemBuyer to be inserted. (required)
        :return: ItemBuyer
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_item_buyer" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `add_item_buyer`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/itemBuyer', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ItemBuyer',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def add_item_buyer_audit(self, item_buyer_id, item_buyer_audit, **kwargs):  # noqa: E501
        """Add new audit for an itemBuyer  # noqa: E501

        Adds an audit to an existing itemBuyer.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.add_item_buyer_audit(item_buyer_id, item_buyer_audit, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to add an audit to (required)
        :param str item_buyer_audit: The audit to add (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.add_item_buyer_audit_with_http_info(item_buyer_id, item_buyer_audit, **kwargs)  # noqa: E501
        else:
            (data) = self.add_item_buyer_audit_with_http_info(item_buyer_id, item_buyer_audit, **kwargs)  # noqa: E501
            return data

    def add_item_buyer_audit_with_http_info(self, item_buyer_id, item_buyer_audit, **kwargs):  # noqa: E501
        """Add new audit for an itemBuyer  # noqa: E501

        Adds an audit to an existing itemBuyer.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.add_item_buyer_audit_with_http_info(item_buyer_id, item_buyer_audit, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to add an audit to (required)
        :param str item_buyer_audit: The audit to add (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['item_buyer_id', 'item_buyer_audit']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_item_buyer_audit" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'item_buyer_id' is set
        if ('item_buyer_id' not in params or
                params['item_buyer_id'] is None):
            raise ValueError("Missing the required parameter `item_buyer_id` when calling `add_item_buyer_audit`")  # noqa: E501
        # verify the required parameter 'item_buyer_audit' is set
        if ('item_buyer_audit' not in params or
                params['item_buyer_audit'] is None):
            raise ValueError("Missing the required parameter `item_buyer_audit` when calling `add_item_buyer_audit`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'item_buyer_id' in params:
            path_params['itemBuyerId'] = params['item_buyer_id']  # noqa: E501
        if 'item_buyer_audit' in params:
            path_params['itemBuyerAudit'] = params['item_buyer_audit']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/itemBuyer/{itemBuyerId}/audit/{itemBuyerAudit}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def add_item_buyer_file(self, item_buyer_id, file_name, **kwargs):  # noqa: E501
        """Attach a file to an itemBuyer  # noqa: E501

        Adds a file to an existing itemBuyer.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.add_item_buyer_file(item_buyer_id, file_name, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to add a file to (required)
        :param str file_name: Name of file (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.add_item_buyer_file_with_http_info(item_buyer_id, file_name, **kwargs)  # noqa: E501
        else:
            (data) = self.add_item_buyer_file_with_http_info(item_buyer_id, file_name, **kwargs)  # noqa: E501
            return data

    def add_item_buyer_file_with_http_info(self, item_buyer_id, file_name, **kwargs):  # noqa: E501
        """Attach a file to an itemBuyer  # noqa: E501

        Adds a file to an existing itemBuyer.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.add_item_buyer_file_with_http_info(item_buyer_id, file_name, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to add a file to (required)
        :param str file_name: Name of file (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['item_buyer_id', 'file_name']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_item_buyer_file" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'item_buyer_id' is set
        if ('item_buyer_id' not in params or
                params['item_buyer_id'] is None):
            raise ValueError("Missing the required parameter `item_buyer_id` when calling `add_item_buyer_file`")  # noqa: E501
        # verify the required parameter 'file_name' is set
        if ('file_name' not in params or
                params['file_name'] is None):
            raise ValueError("Missing the required parameter `file_name` when calling `add_item_buyer_file`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'item_buyer_id' in params:
            path_params['itemBuyerId'] = params['item_buyer_id']  # noqa: E501
        if 'file_name' in params:
            path_params['fileName'] = params['file_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/itemBuyer/{itemBuyerId}/file/{fileName}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def add_item_buyer_tag(self, item_buyer_id, item_buyer_tag, **kwargs):  # noqa: E501
        """Add new tags for an itemBuyer.  # noqa: E501

        Adds a tag to an existing itemBuyer.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.add_item_buyer_tag(item_buyer_id, item_buyer_tag, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to add a tag to (required)
        :param str item_buyer_tag: The tag to add (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.add_item_buyer_tag_with_http_info(item_buyer_id, item_buyer_tag, **kwargs)  # noqa: E501
        else:
            (data) = self.add_item_buyer_tag_with_http_info(item_buyer_id, item_buyer_tag, **kwargs)  # noqa: E501
            return data

    def add_item_buyer_tag_with_http_info(self, item_buyer_id, item_buyer_tag, **kwargs):  # noqa: E501
        """Add new tags for an itemBuyer.  # noqa: E501

        Adds a tag to an existing itemBuyer.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.add_item_buyer_tag_with_http_info(item_buyer_id, item_buyer_tag, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to add a tag to (required)
        :param str item_buyer_tag: The tag to add (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['item_buyer_id', 'item_buyer_tag']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_item_buyer_tag" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'item_buyer_id' is set
        if ('item_buyer_id' not in params or
                params['item_buyer_id'] is None):
            raise ValueError("Missing the required parameter `item_buyer_id` when calling `add_item_buyer_tag`")  # noqa: E501
        # verify the required parameter 'item_buyer_tag' is set
        if ('item_buyer_tag' not in params or
                params['item_buyer_tag'] is None):
            raise ValueError("Missing the required parameter `item_buyer_tag` when calling `add_item_buyer_tag`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'item_buyer_id' in params:
            path_params['itemBuyerId'] = params['item_buyer_id']  # noqa: E501
        if 'item_buyer_tag' in params:
            path_params['itemBuyerTag'] = params['item_buyer_tag']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/itemBuyer/{itemBuyerId}/tag/{itemBuyerTag}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_item_buyer(self, item_buyer_id, **kwargs):  # noqa: E501
        """Delete an itemBuyer  # noqa: E501

        Deletes the itemBuyer identified by the specified id.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.delete_item_buyer(item_buyer_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to be deleted. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.delete_item_buyer_with_http_info(item_buyer_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_item_buyer_with_http_info(item_buyer_id, **kwargs)  # noqa: E501
            return data

    def delete_item_buyer_with_http_info(self, item_buyer_id, **kwargs):  # noqa: E501
        """Delete an itemBuyer  # noqa: E501

        Deletes the itemBuyer identified by the specified id.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.delete_item_buyer_with_http_info(item_buyer_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to be deleted. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['item_buyer_id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_item_buyer" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'item_buyer_id' is set
        if ('item_buyer_id' not in params or
                params['item_buyer_id'] is None):
            raise ValueError("Missing the required parameter `item_buyer_id` when calling `delete_item_buyer`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'item_buyer_id' in params:
            path_params['itemBuyerId'] = params['item_buyer_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/itemBuyer/{itemBuyerId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_item_buyer_tag(self, item_buyer_id, item_buyer_tag, **kwargs):  # noqa: E501
        """Delete a tag for an itemBuyer.  # noqa: E501

        Deletes an existing itemBuyer tag using the specified data.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.delete_item_buyer_tag(item_buyer_id, item_buyer_tag, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to remove tag from (required)
        :param str item_buyer_tag: The tag to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.delete_item_buyer_tag_with_http_info(item_buyer_id, item_buyer_tag, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_item_buyer_tag_with_http_info(item_buyer_id, item_buyer_tag, **kwargs)  # noqa: E501
            return data

    def delete_item_buyer_tag_with_http_info(self, item_buyer_id, item_buyer_tag, **kwargs):  # noqa: E501
        """Delete a tag for an itemBuyer.  # noqa: E501

        Deletes an existing itemBuyer tag using the specified data.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.delete_item_buyer_tag_with_http_info(item_buyer_id, item_buyer_tag, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to remove tag from (required)
        :param str item_buyer_tag: The tag to delete (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['item_buyer_id', 'item_buyer_tag']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_item_buyer_tag" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'item_buyer_id' is set
        if ('item_buyer_id' not in params or
                params['item_buyer_id'] is None):
            raise ValueError("Missing the required parameter `item_buyer_id` when calling `delete_item_buyer_tag`")  # noqa: E501
        # verify the required parameter 'item_buyer_tag' is set
        if ('item_buyer_tag' not in params or
                params['item_buyer_tag'] is None):
            raise ValueError("Missing the required parameter `item_buyer_tag` when calling `delete_item_buyer_tag`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'item_buyer_id' in params:
            path_params['itemBuyerId'] = params['item_buyer_id']  # noqa: E501
        if 'item_buyer_tag' in params:
            path_params['itemBuyerTag'] = params['item_buyer_tag']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/itemBuyer/{itemBuyerId}/tag/{itemBuyerTag}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_duplicate_item_buyer_by_id(self, item_buyer_id, **kwargs):  # noqa: E501
        """Get a duplicated an itemBuyer by id  # noqa: E501

        Returns a duplicated itemBuyer identified by the specified id.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_duplicate_item_buyer_by_id(item_buyer_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to be duplicated. (required)
        :return: ItemBuyer
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.get_duplicate_item_buyer_by_id_with_http_info(item_buyer_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_duplicate_item_buyer_by_id_with_http_info(item_buyer_id, **kwargs)  # noqa: E501
            return data

    def get_duplicate_item_buyer_by_id_with_http_info(self, item_buyer_id, **kwargs):  # noqa: E501
        """Get a duplicated an itemBuyer by id  # noqa: E501

        Returns a duplicated itemBuyer identified by the specified id.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_duplicate_item_buyer_by_id_with_http_info(item_buyer_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to be duplicated. (required)
        :return: ItemBuyer
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['item_buyer_id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_duplicate_item_buyer_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'item_buyer_id' is set
        if ('item_buyer_id' not in params or
                params['item_buyer_id'] is None):
            raise ValueError("Missing the required parameter `item_buyer_id` when calling `get_duplicate_item_buyer_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'item_buyer_id' in params:
            path_params['itemBuyerId'] = params['item_buyer_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/itemBuyer/duplicate/{itemBuyerId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ItemBuyer',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_item_buyer_by_filter(self, **kwargs):  # noqa: E501
        """Search itemBuyers by filter  # noqa: E501

        Returns the list of itemBuyers that match the given filter.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_item_buyer_by_filter(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Query string, used to filter results.
        :param int page: Result page number.  Defaults to 1.
        :param int limit: Maximum results per page.  Defaults to 20.  Max allowed value is 250.
        :param str sort: Sort results by specified field.
        :return: list[ItemBuyer]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.get_item_buyer_by_filter_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_item_buyer_by_filter_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_item_buyer_by_filter_with_http_info(self, **kwargs):  # noqa: E501
        """Search itemBuyers by filter  # noqa: E501

        Returns the list of itemBuyers that match the given filter.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_item_buyer_by_filter_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Query string, used to filter results.
        :param int page: Result page number.  Defaults to 1.
        :param int limit: Maximum results per page.  Defaults to 20.  Max allowed value is 250.
        :param str sort: Sort results by specified field.
        :return: list[ItemBuyer]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter', 'page', 'limit', 'sort']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_item_buyer_by_filter" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filter' in params:
            query_params.append(('filter', params['filter']))  # noqa: E501
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'sort' in params:
            query_params.append(('sort', params['sort']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/itemBuyer/search', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ItemBuyer]',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_item_buyer_by_id(self, item_buyer_id, **kwargs):  # noqa: E501
        """Get an itemBuyer by id  # noqa: E501

        Returns the itemBuyer identified by the specified id.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_item_buyer_by_id(item_buyer_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to be returned. (required)
        :return: ItemBuyer
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.get_item_buyer_by_id_with_http_info(item_buyer_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_item_buyer_by_id_with_http_info(item_buyer_id, **kwargs)  # noqa: E501
            return data

    def get_item_buyer_by_id_with_http_info(self, item_buyer_id, **kwargs):  # noqa: E501
        """Get an itemBuyer by id  # noqa: E501

        Returns the itemBuyer identified by the specified id.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_item_buyer_by_id_with_http_info(item_buyer_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to be returned. (required)
        :return: ItemBuyer
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['item_buyer_id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_item_buyer_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'item_buyer_id' is set
        if ('item_buyer_id' not in params or
                params['item_buyer_id'] is None):
            raise ValueError("Missing the required parameter `item_buyer_id` when calling `get_item_buyer_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'item_buyer_id' in params:
            path_params['itemBuyerId'] = params['item_buyer_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/itemBuyer/{itemBuyerId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ItemBuyer',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_item_buyer_tags(self, item_buyer_id, **kwargs):  # noqa: E501
        """Get the tags for an itemBuyer.  # noqa: E501

        Get all existing itemBuyer tags.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_item_buyer_tags(item_buyer_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to get tags for (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.get_item_buyer_tags_with_http_info(item_buyer_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_item_buyer_tags_with_http_info(item_buyer_id, **kwargs)  # noqa: E501
            return data

    def get_item_buyer_tags_with_http_info(self, item_buyer_id, **kwargs):  # noqa: E501
        """Get the tags for an itemBuyer.  # noqa: E501

        Get all existing itemBuyer tags.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_item_buyer_tags_with_http_info(item_buyer_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param int item_buyer_id: Id of the itemBuyer to get tags for (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['item_buyer_id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_item_buyer_tags" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'item_buyer_id' is set
        if ('item_buyer_id' not in params or
                params['item_buyer_id'] is None):
            raise ValueError("Missing the required parameter `item_buyer_id` when calling `get_item_buyer_tags`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'item_buyer_id' in params:
            path_params['itemBuyerId'] = params['item_buyer_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/itemBuyer/{itemBuyerId}/tag', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_item_buyer(self, body, **kwargs):  # noqa: E501
        """Update an itemBuyer  # noqa: E501

        Updates an existing itemBuyer using the specified data.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.update_item_buyer(body, async=True)
        >>> result = thread.get()

        :param async bool
        :param ItemBuyer body: ItemBuyer to be updated. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.update_item_buyer_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.update_item_buyer_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def update_item_buyer_with_http_info(self, body, **kwargs):  # noqa: E501
        """Update an itemBuyer  # noqa: E501

        Updates an existing itemBuyer using the specified data.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.update_item_buyer_with_http_info(body, async=True)
        >>> result = thread.get()

        :param async bool
        :param ItemBuyer body: ItemBuyer to be updated. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_item_buyer" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `update_item_buyer`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/beta/itemBuyer', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
