# coding: utf-8

"""
    Infoplus API

    Infoplus API.  # noqa: E501

    OpenAPI spec version: v3.0
    Contact: api@infopluscommerce.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Alert(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'type': 'str',
        'level': 'str',
        'message': 'str',
        'link': 'str',
        'link_text': 'str',
        'create_date': 'datetime',
        'modify_date': 'datetime',
        'expiration_date': 'datetime',
        'acknowledge_date': 'datetime',
        'lob_id': 'int',
        'custom_fields': 'dict(str, object)'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'level': 'level',
        'message': 'message',
        'link': 'link',
        'link_text': 'linkText',
        'create_date': 'createDate',
        'modify_date': 'modifyDate',
        'expiration_date': 'expirationDate',
        'acknowledge_date': 'acknowledgeDate',
        'lob_id': 'lobId',
        'custom_fields': 'customFields'
    }

    def __init__(self, id=None, type=None, level=None, message=None, link=None, link_text=None, create_date=None, modify_date=None, expiration_date=None, acknowledge_date=None, lob_id=None, custom_fields=None):  # noqa: E501
        """Alert - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._type = None
        self._level = None
        self._message = None
        self._link = None
        self._link_text = None
        self._create_date = None
        self._modify_date = None
        self._expiration_date = None
        self._acknowledge_date = None
        self._lob_id = None
        self._custom_fields = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.type = type
        self.level = level
        self.message = message
        if link is not None:
            self.link = link
        if link_text is not None:
            self.link_text = link_text
        if create_date is not None:
            self.create_date = create_date
        if modify_date is not None:
            self.modify_date = modify_date
        if expiration_date is not None:
            self.expiration_date = expiration_date
        if acknowledge_date is not None:
            self.acknowledge_date = acknowledge_date
        self.lob_id = lob_id
        if custom_fields is not None:
            self.custom_fields = custom_fields

    @property
    def id(self):
        """Gets the id of this Alert.  # noqa: E501


        :return: The id of this Alert.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Alert.


        :param id: The id of this Alert.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this Alert.  # noqa: E501


        :return: The type of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Alert.


        :param type: The type of this Alert.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def level(self):
        """Gets the level of this Alert.  # noqa: E501


        :return: The level of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this Alert.


        :param level: The level of this Alert.  # noqa: E501
        :type: str
        """
        if level is None:
            raise ValueError("Invalid value for `level`, must not be `None`")  # noqa: E501

        self._level = level

    @property
    def message(self):
        """Gets the message of this Alert.  # noqa: E501


        :return: The message of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Alert.


        :param message: The message of this Alert.  # noqa: E501
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def link(self):
        """Gets the link of this Alert.  # noqa: E501


        :return: The link of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this Alert.


        :param link: The link of this Alert.  # noqa: E501
        :type: str
        """

        self._link = link

    @property
    def link_text(self):
        """Gets the link_text of this Alert.  # noqa: E501


        :return: The link_text of this Alert.  # noqa: E501
        :rtype: str
        """
        return self._link_text

    @link_text.setter
    def link_text(self, link_text):
        """Sets the link_text of this Alert.


        :param link_text: The link_text of this Alert.  # noqa: E501
        :type: str
        """

        self._link_text = link_text

    @property
    def create_date(self):
        """Gets the create_date of this Alert.  # noqa: E501


        :return: The create_date of this Alert.  # noqa: E501
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date):
        """Sets the create_date of this Alert.


        :param create_date: The create_date of this Alert.  # noqa: E501
        :type: datetime
        """

        self._create_date = create_date

    @property
    def modify_date(self):
        """Gets the modify_date of this Alert.  # noqa: E501


        :return: The modify_date of this Alert.  # noqa: E501
        :rtype: datetime
        """
        return self._modify_date

    @modify_date.setter
    def modify_date(self, modify_date):
        """Sets the modify_date of this Alert.


        :param modify_date: The modify_date of this Alert.  # noqa: E501
        :type: datetime
        """

        self._modify_date = modify_date

    @property
    def expiration_date(self):
        """Gets the expiration_date of this Alert.  # noqa: E501


        :return: The expiration_date of this Alert.  # noqa: E501
        :rtype: datetime
        """
        return self._expiration_date

    @expiration_date.setter
    def expiration_date(self, expiration_date):
        """Sets the expiration_date of this Alert.


        :param expiration_date: The expiration_date of this Alert.  # noqa: E501
        :type: datetime
        """

        self._expiration_date = expiration_date

    @property
    def acknowledge_date(self):
        """Gets the acknowledge_date of this Alert.  # noqa: E501


        :return: The acknowledge_date of this Alert.  # noqa: E501
        :rtype: datetime
        """
        return self._acknowledge_date

    @acknowledge_date.setter
    def acknowledge_date(self, acknowledge_date):
        """Sets the acknowledge_date of this Alert.


        :param acknowledge_date: The acknowledge_date of this Alert.  # noqa: E501
        :type: datetime
        """

        self._acknowledge_date = acknowledge_date

    @property
    def lob_id(self):
        """Gets the lob_id of this Alert.  # noqa: E501


        :return: The lob_id of this Alert.  # noqa: E501
        :rtype: int
        """
        return self._lob_id

    @lob_id.setter
    def lob_id(self, lob_id):
        """Sets the lob_id of this Alert.


        :param lob_id: The lob_id of this Alert.  # noqa: E501
        :type: int
        """
        if lob_id is None:
            raise ValueError("Invalid value for `lob_id`, must not be `None`")  # noqa: E501

        self._lob_id = lob_id

    @property
    def custom_fields(self):
        """Gets the custom_fields of this Alert.  # noqa: E501


        :return: The custom_fields of this Alert.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """Sets the custom_fields of this Alert.


        :param custom_fields: The custom_fields of this Alert.  # noqa: E501
        :type: dict(str, object)
        """

        self._custom_fields = custom_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Alert):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
