# coding: utf-8

"""
    Infoplus API

    Infoplus API.  # noqa: E501

    OpenAPI spec version: beta
    Contact: api@infopluscommerce.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class JobType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'client_id': 'int',
        'create_date': 'datetime',
        'modify_date': 'datetime',
        'name': 'str',
        'description': 'str',
        'job_code': 'str',
        'is_active': 'bool',
        'custom_fields': 'dict(str, object)'
    }

    attribute_map = {
        'id': 'id',
        'client_id': 'clientId',
        'create_date': 'createDate',
        'modify_date': 'modifyDate',
        'name': 'name',
        'description': 'description',
        'job_code': 'jobCode',
        'is_active': 'isActive',
        'custom_fields': 'customFields'
    }

    def __init__(self, id=None, client_id=None, create_date=None, modify_date=None, name=None, description=None, job_code=None, is_active=False, custom_fields=None):  # noqa: E501
        """JobType - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._client_id = None
        self._create_date = None
        self._modify_date = None
        self._name = None
        self._description = None
        self._job_code = None
        self._is_active = None
        self._custom_fields = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.client_id = client_id
        if create_date is not None:
            self.create_date = create_date
        if modify_date is not None:
            self.modify_date = modify_date
        self.name = name
        if description is not None:
            self.description = description
        self.job_code = job_code
        if is_active is not None:
            self.is_active = is_active
        if custom_fields is not None:
            self.custom_fields = custom_fields

    @property
    def id(self):
        """Gets the id of this JobType.  # noqa: E501


        :return: The id of this JobType.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this JobType.


        :param id: The id of this JobType.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def client_id(self):
        """Gets the client_id of this JobType.  # noqa: E501


        :return: The client_id of this JobType.  # noqa: E501
        :rtype: int
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this JobType.


        :param client_id: The client_id of this JobType.  # noqa: E501
        :type: int
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def create_date(self):
        """Gets the create_date of this JobType.  # noqa: E501


        :return: The create_date of this JobType.  # noqa: E501
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date):
        """Sets the create_date of this JobType.


        :param create_date: The create_date of this JobType.  # noqa: E501
        :type: datetime
        """

        self._create_date = create_date

    @property
    def modify_date(self):
        """Gets the modify_date of this JobType.  # noqa: E501


        :return: The modify_date of this JobType.  # noqa: E501
        :rtype: datetime
        """
        return self._modify_date

    @modify_date.setter
    def modify_date(self, modify_date):
        """Sets the modify_date of this JobType.


        :param modify_date: The modify_date of this JobType.  # noqa: E501
        :type: datetime
        """

        self._modify_date = modify_date

    @property
    def name(self):
        """Gets the name of this JobType.  # noqa: E501


        :return: The name of this JobType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this JobType.


        :param name: The name of this JobType.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this JobType.  # noqa: E501


        :return: The description of this JobType.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this JobType.


        :param description: The description of this JobType.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def job_code(self):
        """Gets the job_code of this JobType.  # noqa: E501


        :return: The job_code of this JobType.  # noqa: E501
        :rtype: str
        """
        return self._job_code

    @job_code.setter
    def job_code(self, job_code):
        """Sets the job_code of this JobType.


        :param job_code: The job_code of this JobType.  # noqa: E501
        :type: str
        """
        if job_code is None:
            raise ValueError("Invalid value for `job_code`, must not be `None`")  # noqa: E501

        self._job_code = job_code

    @property
    def is_active(self):
        """Gets the is_active of this JobType.  # noqa: E501


        :return: The is_active of this JobType.  # noqa: E501
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this JobType.


        :param is_active: The is_active of this JobType.  # noqa: E501
        :type: bool
        """

        self._is_active = is_active

    @property
    def custom_fields(self):
        """Gets the custom_fields of this JobType.  # noqa: E501


        :return: The custom_fields of this JobType.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._custom_fields

    @custom_fields.setter
    def custom_fields(self, custom_fields):
        """Sets the custom_fields of this JobType.


        :param custom_fields: The custom_fields of this JobType.  # noqa: E501
        :type: dict(str, object)
        """

        self._custom_fields = custom_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
