# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class PickFaceAssignment(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        PickFaceAssignment - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'warehouse_id': 'int',
            'location_id': 'int',
            'replenishment_point': 'int',
            'max_quantity': 'int',
            'create_date': 'datetime',
            'modify_date': 'datetime',
            'sku': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'warehouse_id': 'warehouseId',
            'location_id': 'locationId',
            'replenishment_point': 'replenishmentPoint',
            'max_quantity': 'maxQuantity',
            'create_date': 'createDate',
            'modify_date': 'modifyDate',
            'sku': 'sku'
        }

        self._id = None
        self._warehouse_id = None
        self._location_id = None
        self._replenishment_point = None
        self._max_quantity = None
        self._create_date = None
        self._modify_date = None
        self._sku = None

    @property
    def id(self):
        """
        Gets the id of this PickFaceAssignment.


        :return: The id of this PickFaceAssignment.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this PickFaceAssignment.


        :param id: The id of this PickFaceAssignment.
        :type: int
        """
        self._id = id

    @property
    def warehouse_id(self):
        """
        Gets the warehouse_id of this PickFaceAssignment.


        :return: The warehouse_id of this PickFaceAssignment.
        :rtype: int
        """
        return self._warehouse_id

    @warehouse_id.setter
    def warehouse_id(self, warehouse_id):
        """
        Sets the warehouse_id of this PickFaceAssignment.


        :param warehouse_id: The warehouse_id of this PickFaceAssignment.
        :type: int
        """
        self._warehouse_id = warehouse_id

    @property
    def location_id(self):
        """
        Gets the location_id of this PickFaceAssignment.


        :return: The location_id of this PickFaceAssignment.
        :rtype: int
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id):
        """
        Sets the location_id of this PickFaceAssignment.


        :param location_id: The location_id of this PickFaceAssignment.
        :type: int
        """
        self._location_id = location_id

    @property
    def replenishment_point(self):
        """
        Gets the replenishment_point of this PickFaceAssignment.


        :return: The replenishment_point of this PickFaceAssignment.
        :rtype: int
        """
        return self._replenishment_point

    @replenishment_point.setter
    def replenishment_point(self, replenishment_point):
        """
        Sets the replenishment_point of this PickFaceAssignment.


        :param replenishment_point: The replenishment_point of this PickFaceAssignment.
        :type: int
        """
        self._replenishment_point = replenishment_point

    @property
    def max_quantity(self):
        """
        Gets the max_quantity of this PickFaceAssignment.


        :return: The max_quantity of this PickFaceAssignment.
        :rtype: int
        """
        return self._max_quantity

    @max_quantity.setter
    def max_quantity(self, max_quantity):
        """
        Sets the max_quantity of this PickFaceAssignment.


        :param max_quantity: The max_quantity of this PickFaceAssignment.
        :type: int
        """
        self._max_quantity = max_quantity

    @property
    def create_date(self):
        """
        Gets the create_date of this PickFaceAssignment.


        :return: The create_date of this PickFaceAssignment.
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date):
        """
        Sets the create_date of this PickFaceAssignment.


        :param create_date: The create_date of this PickFaceAssignment.
        :type: datetime
        """
        self._create_date = create_date

    @property
    def modify_date(self):
        """
        Gets the modify_date of this PickFaceAssignment.


        :return: The modify_date of this PickFaceAssignment.
        :rtype: datetime
        """
        return self._modify_date

    @modify_date.setter
    def modify_date(self, modify_date):
        """
        Sets the modify_date of this PickFaceAssignment.


        :param modify_date: The modify_date of this PickFaceAssignment.
        :type: datetime
        """
        self._modify_date = modify_date

    @property
    def sku(self):
        """
        Gets the sku of this PickFaceAssignment.


        :return: The sku of this PickFaceAssignment.
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """
        Sets the sku of this PickFaceAssignment.


        :param sku: The sku of this PickFaceAssignment.
        :type: str
        """
        self._sku = sku

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

