# coding: utf-8

"""
    Infoplus API

    Infoplus API.  # noqa: E501

    OpenAPI spec version: beta
    Contact: api@infopluscommerce.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ServiceType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'service_type': 'str',
        'label': 'str',
        'full_entity_class_name': 'str'
    }

    attribute_map = {
        'service_type': 'serviceType',
        'label': 'label',
        'full_entity_class_name': 'fullEntityClassName'
    }

    def __init__(self, service_type=None, label=None, full_entity_class_name=None):  # noqa: E501
        """ServiceType - a model defined in Swagger"""  # noqa: E501

        self._service_type = None
        self._label = None
        self._full_entity_class_name = None
        self.discriminator = None

        self.service_type = service_type
        self.label = label
        if full_entity_class_name is not None:
            self.full_entity_class_name = full_entity_class_name

    @property
    def service_type(self):
        """Gets the service_type of this ServiceType.  # noqa: E501


        :return: The service_type of this ServiceType.  # noqa: E501
        :rtype: str
        """
        return self._service_type

    @service_type.setter
    def service_type(self, service_type):
        """Sets the service_type of this ServiceType.


        :param service_type: The service_type of this ServiceType.  # noqa: E501
        :type: str
        """
        if service_type is None:
            raise ValueError("Invalid value for `service_type`, must not be `None`")  # noqa: E501

        self._service_type = service_type

    @property
    def label(self):
        """Gets the label of this ServiceType.  # noqa: E501


        :return: The label of this ServiceType.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this ServiceType.


        :param label: The label of this ServiceType.  # noqa: E501
        :type: str
        """
        if label is None:
            raise ValueError("Invalid value for `label`, must not be `None`")  # noqa: E501

        self._label = label

    @property
    def full_entity_class_name(self):
        """Gets the full_entity_class_name of this ServiceType.  # noqa: E501


        :return: The full_entity_class_name of this ServiceType.  # noqa: E501
        :rtype: str
        """
        return self._full_entity_class_name

    @full_entity_class_name.setter
    def full_entity_class_name(self, full_entity_class_name):
        """Sets the full_entity_class_name of this ServiceType.


        :param full_entity_class_name: The full_entity_class_name of this ServiceType.  # noqa: E501
        :type: str
        """

        self._full_entity_class_name = full_entity_class_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
